' This excel macro will take the data from the 
' Simulation run and make a graph to display the data
' NOTE: This marco is very specific to that scenario
' and will most likely not work on other scenarios
' 
' USAGE: Once the graph is made, export
' the data to a spread sheet and run this maco.
' You should have a graph of the data in the end.
' 
' Author: Remo Cocco and the almight and powerful Excel
' Date: 2011.05.11
'
' TODO: Clean up the code and make it more robust.
'

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' BELOW IS CODE GENERATED BY EXCEL
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' This excel macro will take the data from the
' Simulation run and make a graph to display the data
' NOTE: This marco is very specific to that scenario
' and will most likely not work on other scenarios
'
' USAGE: Once the graph is made, export
' the data to a spread sheet and run this maco.
' You should have a graph of the data in the end.
'
' Author: Remo Cocco and the almight and powerful Excel
' Author: Malik Ahmed
' Date: 2011.05.11
'
' TODO: Clean up the code and make it more robust.
'

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
' BELOW IS CODE GENERATED BY EXCEL
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Sub MakeGeoAODVGraph()
'
' MakeGeoAODVGraph Macro
'

'
    Columns("A:A").Select
    Selection.ClearContents
    Rows("1:500").Select
    Selection.ClearContents
    ActiveWindow.SmallScroll Down:=78
    ActiveWindow.SmallScroll ToRight:=3
    ActiveWindow.SmallScroll Down:=27
    ActiveWindow.SmallScroll ToRight:=3
    ActiveWindow.SmallScroll Down:=48
    ActiveWindow.SmallScroll ToRight:=-6
    ActiveWindow.SmallScroll Down:=333
    Rows("502:502").Select
    Selection.ClearContents
    Rows("501:501").Select
    Selection.Cut
    ActiveWindow.SmallScroll Down:=-504
    Rows("12:12").Select
    ActiveSheet.Paste
    Range("A2").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "Speed"
    Range("A3").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "0"
    Range("A4").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "1"
    Range("A5").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "5"
    Range("A6").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "10"
    Range("A7").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "20"
    Range("A8").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "Random"
    Range("B2").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "AODV"
    Range("C2").Select
    Selection.Font.Bold = True
    ActiveCell.FormulaR1C1 = "LAR Zone"
    Range("D2").Select
    ActiveCell.FormulaR1C1 = "LAR Distance"
    With ActiveCell.Characters(Start:=1, Length:=12).Font
        .Name = "Calibri"
        .FontStyle = "Bold"
        .Size = 11
        .Strikethrough = False
        .Superscript = False
        .Subscript = False
        .OutlineFont = False
        .Shadow = False
        .Underline = xlUnderlineStyleNone
        .ThemeColor = xlThemeColorLight1
        .TintAndShade = 0
        .ThemeFont = xlThemeFontMinor
    End With
    Range("E2").Select
    ActiveCell.FormulaR1C1 = "GeoAODV"
    With ActiveCell.Characters(Start:=1, Length:=7).Font
        .Name = "Calibri"
        .FontStyle = "Bold"
        .Size = 11
        .Strikethrough = False
        .Superscript = False
        .Subscript = False
        .OutlineFont = False
        .Shadow = False
        .Underline = xlUnderlineStyleNone
        .ThemeColor = xlThemeColorLight1
        .TintAndShade = 0
        .ThemeFont = xlThemeFontMinor
    End With
    Range("F2").Select
    ActiveCell.FormulaR1C1 = "GeoAODV Rotate"
    With ActiveCell.Characters(Start:=1, Length:=14).Font
        .Name = "Calibri"
        .FontStyle = "Bold"
        .Size = 11
        .Strikethrough = False
        .Superscript = False
        .Subscript = False
        .OutlineFont = False
        .Shadow = False
        .Underline = xlUnderlineStyleNone
        .ThemeColor = xlThemeColorLight1
        .TintAndShade = 0
        .ThemeFont = xlThemeFontMinor
    End With
    Range("F3").Select
    Columns("F:F").EntireColumn.AutoFit
    Columns("D:D").EntireColumn.AutoFit
    Columns("E:E").EntireColumn.AutoFit
    Range("B12:F12").Select
    Selection.Cut
    Range("B3").Select
    ActiveSheet.Paste
    Range("G12:K12").Select
    Selection.Cut
    Range("B4").Select
    ActiveSheet.Paste
    Range("L12:P12").Select
    Selection.Cut
    Range("B5").Select
    ActiveSheet.Paste
    Range("Q12:U12").Select
    Selection.Cut
    ActiveWindow.SmallScroll ToRight:=-3
    Range("B6").Select
    ActiveSheet.Paste
    ActiveWindow.SmallScroll ToRight:=12
    ActiveWindow.SmallScroll Down:=6
    Range("V12:Z12").Select
    Selection.Cut
    ActiveWindow.SmallScroll ToRight:=-12
    ActiveWindow.SmallScroll Down:=-24
    Range("B7").Select
    ActiveSheet.Paste
    ActiveWindow.SmallScroll ToRight:=12
    ActiveWindow.SmallScroll Down:=-3
    Range("AA12:AE12").Select
    Selection.Cut
    ActiveWindow.SmallScroll ToRight:=-12
    Range("B8").Select
    ActiveSheet.Paste
    Range("B1:F1").Select
    With Selection
        .HorizontalAlignment = xlCenter
        .VerticalAlignment = xlBottom
        .WrapText = False
        .Orientation = 0
        .AddIndent = False
        .IndentLevel = 0
        .ShrinkToFit = False
        .ReadingOrder = xlContext
        .MergeCells = False
    End With
    Selection.Merge
    ActiveCell.FormulaR1C1 = "TITLE"
    Range("B1:F1").Select
    Selection.Font.Bold = True
    Range("A1:F8").Select

    Dim r As Range
    Set r = ActiveSheet.Range("A2:F8")
    ActiveChart.SetSourceData Source:=r
    ActiveChart.ChartType = xlLineMarkers
    ActiveChart.Legend.Select
    ActiveSheet.ChartObjects("Chart 1").Activate
    ActiveChart.PlotArea.Select
    ActiveSheet.ChartObjects("Chart 1").Activate
    ActiveChart.Legend.Select
    r.Select
    ActiveSheet.Shapes.AddChart.Select
    ActiveChart.SetSourceData Source:=r
    ActiveChart.ChartType = xlLineMarkers
End Sub
